--SELECT EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_NAME
--FROM hr.Employees--
--INNER JOIN hr.Departments ON hr.Employees.DEPARTMENT_ID = hr.Departments.DEPARTMENT_ID;--


--SELECT EMPLOYEE_ID, MANAGER_ID 
--FROM hr.Employees 
--WHERE MANAGER_ID IS NOT NULL;

--SELECT SUBSTR(PHONE_NUMBER, 1, 3) AS OPERATOR, COUNT(*) AS Total
--FROM hr.Employees 
--GROUP BY SUBSTR(PHONE_NUMBER, 1, 3);

/*CREATE TABLE emp (
    EMPLOYEE_ID NUMBER PRIMARY KEY,
    FIRST_NAME VARCHAR2(50),
    LAST_NAME VARCHAR2(50),
    EMAIL VARCHAR2(100),
    PHONE_NUMBER VARCHAR2(20),
    HIRE_DATE DATE,
    JOB_ID VARCHAR2(10),
    SALARY NUMBER(8, 2),
    MANAGER_ID NUMBER,
    DEPARTMENT_ID NUMBER
);

INSERT INTO emp (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, MANAGER_ID, DEPARTMENT_ID) 
VALUES (1, 'John', 'Doe', 'john.doe@example.com', '555-1234', TO_DATE('2023-01-15', 'YYYY-MM-DD'), 'IT_PROG', 60000, 101, 10);

UPDATE emp
SET SALARY = 65000 , PHONE_NUMBER = '444-4444'
WHERE FIRST_NAME = 'John'

DELETE FROM emp
WHERE FIRST_NAME = 'John';

DROP TABLE emp
*/
/*SELECT CONCAT(
         CONCAT(
           SUBSTR(FIRST_NAME, 1, 2),
           RPAD(' ', LENGTH(FIRST_NAME) - 2, '*')
         ),
         CONCAT(
           SUBSTR(LAST_NAME, 1, 2),
           RPAD(' ', LENGTH(LAST_NAME) - 2, '*')
         )
       ) AS "CUSTOMER NAME"
FROM hr.Employees;*/


--SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,ROUND(MONTHS_BETWEEN(SYSDATE, HIRE_DATE)) FROM hr.Employees

/*SELECT 
  EMPLOYEE_ID,
  DECODE(JOB_ID, 
         'AD_PRES', 'A',
         'ST_MAN', 'B',
         'IT_PROG', 'C',
         'SA_REP', 'D',
         'ST_CLERK', 'E',
         '0') AS JOB_DESCRIPTION
FROM 
  hr.Employees;*/
/*SELECT 
  EMPLOYEE_ID,
  CASE JOB_ID
    WHEN 'AD_PRES' THEN 'A'
    WHEN 'ST_MAN' THEN 'B'
    WHEN 'IT_PROG' THEN 'C'
    WHEN 'SA_REP' THEN 'D'
    WHEN 'ST_CLERK' THEN 'E'
    ELSE '0'
  END AS JOB_DESCRIPTION
FROM 
  hr.Employees;*/

/*
SELECT EMPLOYEE_ID, LAST_NAME
FROM hr.Employees
WHERE LAST_NAME LIKE '%a%';*/



);
/*
CREATE TABLE MY_EMP_TABLE (
    EMPLOYEE_ID NUMBER PRIMARY KEY,
    FIRST_NAME VARCHAR2(50),
    LAST_NAME VARCHAR2(50),
    SALARY NUMBER

INSERT INTO MY_EMP_TABLE (EMPLOYEE_ID, LAST_NAME, FIRST_NAME, SALARY)
VALUES (1, 'Black', 'John', 1100);

INSERT INTO MY_EMP_TABLE (EMPLOYEE_ID, LAST_NAME, FIRST_NAME, SALARY)
VALUES (2, 'White', 'Kent', 1300);

INSERT INTO MY_EMP_TABLE (EMPLOYEE_ID, LAST_NAME, FIRST_NAME, SALARY)
VALUES (3, 'Orange', 'David', 1700);

INSERT INTO MY_EMP_TABLE (EMPLOYEE_ID, LAST_NAME, FIRST_NAME, SALARY)
VALUES (4, 'Pink', 'Alissa', 1900);

UPDATE MY_EMP_TABLE
SET SALARY = SALARY * 1.10;


DELETE MY_EMP_TABLE
WHERE FIRST_NAME = 'David'


TRUNCATE TABLE MY_EMP_TABLE

*/



















