ALTER TABLE hr.Employees
ADD MAX_SALARY NUMBER;

UPDATE hr.Employees
SET MAX_SALARY = (SELECT MAX(SALARY) FROM hr.Employees); 

DELETE FROM hr.Employees
WHERE SALARY = (SELECT MIN(SALARY) FROM hr.Employees);

CREATE INDEX DPR_NAME_IDX ON DEPARTMENT(DEPARTMENT_NAME);

ALTER TABLE hr.Employees;
ADD CNSTR_SALARY NUMBER CHECK (SALARY>10000 BETWEEN SALARY<100000);

DROP INDEX DPR_NAME_IDX;

ALTER TABLE hr.Employees DROP CONSTRAINT CNSTR_SALARY;
ALTER TABLE hr.Employees ENABLE CONSTRAINT CNSTR_SALARY;
ALTER TABLE hr.Employees DISABLE CONSTRAINT CNSTR_SALARY;


CREATE TABLE MY_DEP AS
SELECT DISTINCT DEPARTMENT_ID
FROM hr.Employees;

ALTER TABLE MY_DEP
ADD DEPARTMENT_NAME VARCHAR(20);

MERGE INTO MY_DEP mp
USING DEPARTMENT d
ON mp.DEPARTMENT_NAME = d.DEPARTMENT_NAME
WHEN MATCHED THEN
UPDATE SET
mp.DEPARTMENT_ID=d.DEPARTMENT_ID, mp.DEPARTMENT_NAME=d.DEPARTMENT_NAME
WHEN NOT MATCHED THEN
INSERT(DEPARTMENT_ID,DEPARTMENT_NAME) VALUES(d.DEPARTMENT_ID,d.DEPARTMENT_NAME)

WITH EMP_NAME AS(
    SELECT FIRST_NAME,LAST_NAME,JOB_ID,DEPARTMENT_ID FROM hr.Employees
	WHERE LIKE '%S'
)

SELECT JOB_TITLE,MIN(SALARY),MAX(SALARY) FROM EMP_NAME;

ALTER TABLE EMP_NAME
ADD DEPARTMENT_NAME VARCHAR(20);

SELECT CONCAT(FIRST_NAME,CONCAT(' ',LAST_NAME)) AS FULL_NAME FROM EMP_NAME;


" ROLLBACK: Bring back last changes since last COMMIT "
" COMMIT: Permanently save all changes "
